---
title: "Photo_crd_Access"
author: "MThompson"
date: "2024-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries


```{r Libraries}

list.of.packages <- c(
  "stringr",
  "here",
  "terra",
  "future",
  "class",
  "reshape",
  "ggplot2",
  "sf",
  "XML",
  "exiftoolr",
  "curl",
  "RCurl",
  "httr",
  "ncdf4",
  "future",
  "rsi",
  "rstac",
  "doParallel",
  "usethis",
  "RColorBrewer",
  "dismo",
  "randomForest",
  "SSDM",
  "ranger",
  "tmap",
  "BiodiversityR",
  "tidyverse",
  "viridis",
  "tmaptools"
)

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

if(length(new.packages) > 0){
  install.packages(new.packages, dep=TRUE)
}

#loading packages
for(package.i in list.of.packages){
  suppressPackageStartupMessages(
    library(
      package.i, 
      character.only = TRUE
    )
  )
}

#Developer version needed
#install.packages("terra", repos = "https://rspatial.r-universe.dev")
#library(terra)

# Local
install.packages(paste0(here("Inputs","ClimateNA"),"/ClimateNAr_1.2.0.zip"),
                 repos = NULL,
                 type = "win.binary")
library(ClimateNAr)
n.cores <- future::availableCores() - 1

```


# Coordinates from digital image records

I had a directory of photos with coordinates stored in the metadata. Coordinates were cross referenced with maps, field notes, and GPS records. This was a simple way to view the new records and retrieve the coordinate data.

```{r Photos echo=FALSE, eval=FALSE}
install_exiftool()
file_names <- list.files(here("Inputs","AmphibianLocations"),
                         pattern = "*.jpg", full.names=TRUE)

figls <- list()

for(i in 1:length(file_names)){
  figls[[i]] <- exif_read(path = file_names[i],
                        tags=c("GPSDateStamp",
                               "GPSLatitude",
                               "GPSLongitude"))
}

# Some images do not have the data
# 1,12 miss Date, lat, lon
figls[[1]][,c(2:4)] = NA
colnames(figls[[1]]) = c("SourceFile",
                         "GPSDateStamp",
                         "GPSLatitude",
                         "GPSLongitude")
figls[[12]][,c(2:4)] = NA
colnames(figls[[12]]) = c("SourceFile",
                          "GPSDateStamp",
                          "GPSLatitude",
                          "GPSLongitude")

# 6:8,10, miss date
figls[[6]][,c(3:4)] = figls[[6]][,c(2:3)]
figls[[6]][,2] = NA
colnames(figls[[6]]) = c("SourceFile",
                         "GPSDateStamp",
                         "GPSLatitude",
                         "GPSLongitude")

figls[[7]][,c(3:4)] = figls[[7]][,c(2:3)]
figls[[7]][,2] = NA
colnames(figls[[7]]) = c("SourceFile",
                         "GPSDateStamp",
                         "GPSLatitude",
                         "GPSLongitude")
figls[[8]][,c(3:4)] = figls[[8]][,c(2:3)]
figls[[8]][,2] = NA
colnames(figls[[8]]) = c("SourceFile",
                         "GPSDateStamp",
                         "GPSLatitude",
                         "GPSLongitude")

figls[[10]][,c(3:4)] = figls[[10]][,c(2:3)]
figls[[10]][,2] = NA
colnames(figls[[10]]) = c("SourceFile",
                         "GPSDateStamp",
                         "GPSLatitude",
                         "GPSLongitude")

fig_df <- do.call(rbind.data.frame, figls)

fig_df[12,2] = "2023:6:13"
fig_df[12,3] = "57.385949"
fig_df[12,4] = "-127.245555"

# Palmer toad
fig_df[1,2] = "2022:9:10"
fig_df[1,3] = "57.346881"
fig_df[1,4] = "-127.148412"

figls[[i]] <- exif_read(path = file_names[i],
                        tags=c("GPSDateStamp",
                               "GPSLatitude",
                               "GPSLongitude"))
fig_df[6,2] = "2023:6:13"

fig_df[1] <- list.files(here("Amphibian Database_MDT","New"),
                        pattern = "*.jpg")
fig_df[c(6:8),2] <- "2023:06:26"
fig_df[10,2] <- "2023:06:27"
fig_df[,3] <- as.numeric(fig_df[,3])
fig_df[,4] <- as.numeric(fig_df[,4])
fig_df$species <- c("ANBO"
                    ,"ANBO",
                    "ANBO",
                    "ANBO",
                    "ANBO",
                    "RALU",
                    "RALU",
                    "RALU",
                    "ANBO",
                    "RALU",
                    "ANBO",
                    "RALU")
fig_df$stage <- c("adult",
                  "tadpole",
                  "tadpole",
                  "tadpole",
                  "tadpole",
                  "adult",
                  "adult",
                  "adult",
                  "tadpole",
                  "adult",
                  "adult",
                  "adult")

fig_df <- as.data.frame(fig_df)

Amphibians <- terra::vect(fig_df,geom=c("GPSLongitude",
                                 "GPSLatitude"),
                   crs="epsg:32610")

Amphibians <- project(Amphibians, "epsg:32610")

writeVector(Amphibians,
            paste0(here("Inputs","AmphibianLocations"),
                   "/Amphibians_Layers.shp"),
            overwrite=TRUE)
```
